version: '3.8'

services:
    traffic-gate_frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: traffic-gate_frontend
        ports:
            - '4173:4173'
        restart: unless-stopped
